language: python
python:
  - "3.6"
sudo: false
dist: trusty
cache:
  pip: true
  directories:
    - $HOME/.npm
install:
- python -m pip install -q -U pip
- pip install notebook
- pip install cookiecutter
- pip install --pre -U jupyterlab
script:
- cookiecutter . --no-input
- cd myextension
- npm install
- jupyter labextension install .
- jupyter lab clean
- jupyter labextension link .
- python -m jupyterlab.browser_check
