language: python
sudo: false
dist: trusty
cache:
  pip: true
  directories:
    - $HOME/.npm
install:
- pip install -U -q pip
- pip install notebook
- pip install cookiecutter
- pip install jupyterlab
script:
- cookiecutter . --no-input
- cd myextension
- npm install
- jupyter labextension install .
- jupyter lab clean
- jupyter labextension link .
- python -m jupyterlab.browser_check
